data:
    path_train: '/pscratch/sd/a/ashodkh/image_photo_z/candels_combined_catalog_bright_without_test_val.hdf5'
    path_val: '/pscratch/sd/a/ashodkh/image_photo_z/candels_val_catalog.hdf5'
    path_band_mads: '/global/homes/a/ashodkh/image_photo_z/notebooks/candels_band_mads.npy'
    n_filters: 4
    batch_size: 256
    num_workers: 28
    label_f: 1

augmentations:
    reddening_R: [2.471, 1.526, 0.726, 0.512]
    crop_dim: 64
    jitter_lim: 4
    gaussian_transform: true

model:
    encoder_name: 'convnext_tiny'
    latent_d: 128
    projection_d: 64
    redshift_mlp_hidden_layers: [256,128,128,128,128,64,1]
    color_mlp_hidden_layers: [256,128,128,128,128,64,4]
    queue_size: 60000
    temperature: 0.1

training:
    epochs: 1550
    learning_rate: 0.001
    momentum: 0.999
    cl_loss_weight: 0.0025
    redshift_loss_weight: 1
    color_loss_weight: 1
    lr_scheduler:
        type: 'cosine' # cosine, multistep, or warmupcosine
        cosine:
            T_max: 500
            eta_min: 0.0000001
        multistep:
            milestones: [1500]
            gamma: 0.1
        warmupcosine:
            warmup_epochs: 200
            half_period: 900
            min_lr: 0.000001


logging_and_checkpoint:
    dir_log: "/global/homes/a/ashodkh/image_photo_z/scripts/lightning_logs_candels/semi_supervised"
    dir_checkpoint: '/pscratch/sd/a/ashodkh/image_photo_z/model_weights/'
    every_n_epochs: 1
    